# Generated by Django 5.2 on 2025-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Text'),
        ),
    ]
